log:
  exp_name: basketball
guide:
  text: 
    - "A basketball with a classic orange pebbled leather texture and black grooves, {} view"
    - "A basketball with a glossy, polished marble finish in black and white, {} view"
    - "A basketball made of rough sandpaper-like material with uneven patterns, {} view"
    - "A futuristic basketball with a glowing neon grid texture in shades of blue, {} view"
    - "A basketball with a furry, soft fabric texture, like a fuzzy blanket, {} view"
  append_direction: True
  shape_path: shapes/basketball.obj
optim:
  seed: 3
