log:
  exp_name: bunny
guide:
  text: 
    - "A bunny with a fluffy and realistic fur texture in shades of white and gray, {} view"
    - "A bunny made of smooth, shiny porcelain with delicate hand-painted details, {} view"
    - "A bunny covered in a rough stone texture, like a carved granite statue, {} view"
    - "A bunny with a soft, velvety texture and subtle pastel colors, {} view"
    - "A bunny made entirely of metallic gold with a brushed finish, {} view"
  append_direction: True
  shape_path: shapes/bunny.obj
optim:
  seed: 3
