log:
  exp_name: cat
guide:
  text: 
    - "A cat with a realistic short fur texture in shades of orange and white, {} view"
    - "A cat made of smooth, glossy black marble with subtle white veining, {} view"
    - "A cat with a shiny metallic texture, reflecting light like polished silver, {} view"
    - "A cat covered in a woven fabric texture, like a hand-knitted toy, {} view"
    - "A cat with a transparent jelly-like texture, glowing faintly in green, {} view"
  append_direction: True
  shape_path: shapes/cat.obj
optim:
  seed: 3
