log:
  exp_name: nascar
guide:
  text: 
    - "A NASCAR car with glossy paint and bright red and blue stripes, {} view"
    - "A NASCAR car with weathered surfaces, scratches, and dirt marks, {} view"
    - "A NASCAR car with a sleek black and silver carbon fiber texture, {} view"
    - "A NASCAR car with a metallic finish and neon sponsor logos, {} view"
    - "A NASCAR car with a classic checkered flag design in white and black, {} view"
  diffusion_name: stabilityai/stable-diffusion-2-depth
  shape_scale: 0.6
  append_direction: True
  shape_path: shapes/nascar.obj
  texture_resolution: 1024
  guidance_scale: 10
  texture_interpolation_mode: 'bilinear'
optim:
  seed: 2
render:
  front_offset: 0
