log:
  exp_name: turtle
guide:
  text: 
    - "A turtle with a realistic shell featuring green and brown hexagonal patterns, {} view"
    - "A turtle with a vibrant green cartoon-style shell, {} view"
    - "A turtle carved from stone with an ancient texture, {} view"
    - "A turtle with a cybernetic metallic shell and glowing lines, {} view"
    - "A turtle with a golden shell engraved with decorative patterns, {} view"
  append_direction: True
  shape_path: shapes/turtle.obj
optim:
  seed: 3
