log:
  exp_name: vase
guide:
  text: 
    - "A vase with classic ceramic design and blue floral patterns, {} view"
    - "A vase made of rustic clay with earthy tones and visible cracks, {} view"
    - "A vase made of glossy glass with a transparent gradient, {} view"
    - "A vase with a brushed copper metallic finish, {} view"
    - "A vase painted with bright abstract designs, {} view"
  append_direction: True
  shape_path: shapes/vase.obj
optim:
  seed: 3
