log:
  exp_name: basketball_1
guide:
  text: A basketball with a classic orange pebbled leather texture and black grooves, {} view
  append_direction: true
  shape_path: shapes/basketball.obj
optim:
  seed: 3
