log:
  exp_name: basketball_5
guide:
  text: A basketball with a furry, soft fabric texture, like a fuzzy blanket, {} view
  append_direction: true
  shape_path: shapes/basketball.obj
optim:
  seed: 3
