log:
  exp_name: doughnut_5
guide:
  text: A doughnut made of smooth, translucent glass with pastel-colored swirls, {} view
  append_direction: true
  shape_path: shapes/doughnut.obj
optim:
  seed: 3
