log:
  exp_name: doughnut_4
guide:
  text: A doughnut with a rough, sugary coating texture, sparkling in the light, {} view
  append_direction: true
  shape_path: shapes/doughnut.obj
optim:
  seed: 3
