log:
  exp_name: nascar_3
guide:
  text: A NASCAR car with a sleek black and silver carbon fiber texture, {} view
  diffusion_name: stabilityai/stable-diffusion-2-depth
  shape_scale: 0.6
  append_direction: true
  shape_path: shapes/nascar.obj
  texture_resolution: 1024
  guidance_scale: 10
  texture_interpolation_mode: bilinear
optim:
  seed: 2
render:
  front_offset: 0
