log:
  exp_name: bunny_t3
guide:
  text: A bunny covered in a cartoon-style rough stone texture, like a carved granite statue, {} view
  append_direction: true
  shape_path: shapes/bunny.obj
optim:
  seed: 3
