log:
  exp_name: bunny_t2
guide:
  text: A bunny made of cartoon-style smooth, shiny porcelain with delicate hand-painted details, {} view
  append_direction: true
  shape_path: shapes/bunny.obj
optim:
  seed: 3
