log:
  exp_name: cat_t3
guide:
  text: A cat with a cartoon-style shiny metallic texture, reflecting light like polished silver, {} view
  append_direction: true
  shape_path: shapes/cat.obj
optim:
  seed: 3
