log:
  exp_name: cat_t5
guide:
  text: A cat with a cartoon-style transparent jelly-like texture, glowing faintly in green, {} view
  append_direction: true
  shape_path: shapes/cat.obj
optim:
  seed: 3
