log:
  exp_name: cat_t2
guide:
  text: A cat made of cartoon-style smooth, glossy black marble with subtle white veining, {} view
  append_direction: true
  shape_path: shapes/cat.obj
optim:
  seed: 3
