log:
  exp_name: cow_t5
guide:
  text: A cow with a cartoon-style cracked, dried mud texture, as if it's made from clay, {} view
  append_direction: true
  shape_path: shapes/cow.obj
optim:
  seed: 3
