log:
  exp_name: fish_t3
guide:
  text: A fish with a cartoon-style glowing neon texture, as if swimming in a futuristic aquarium, {} view
  append_direction: true
  shape_path: shapes/fish.obj
optim:
  seed: 3
