log:
  exp_name: fish_t4
guide:
  text: A fish covered in cartoon-style rough, volcanic rock texture with glowing orange cracks, {} view
  append_direction: true
  shape_path: shapes/fish.obj
optim:
  seed: 3
