log:
  exp_name: horse_t3
guide:
  text: A horse with a cartoon-style velvety texture, soft to the touch and rich in color, {} view
  append_direction: true
  shape_path: shapes/horse.obj
optim:
  seed: 3
