log:
  exp_name: horse_t1
guide:
  text: A horse with a cartoon-style sleek, shiny coat in shades of deep brown and black, {} view
  append_direction: true
  shape_path: shapes/horse.obj
optim:
  seed: 3
