log:
  exp_name: rabbit_t1
guide:
  text: A rabbit with cartoon-style fluffy fur texture in shades of white and grey, {} view
  append_direction: true
  shape_path: shapes/rabbit.obj
optim:
  seed: 3
